import os
from time import sleep
import configparser

config = configparser.ConfigParser()
config.read('config.ini')

print("well this part is very shitty coded tho.. deal with it")
sleep(0.4)
print("for this part we will need an alt account that will be in the same server + we will need to use channel ids so you better manage the alt account in a web browser")
sleep(0.4)
print("first of all, enter the alt account login details (don't worry no one will have the information it's safe")
print("also make sure you don't have 2fa enabled on the account")
print('the program will login into the account and download all the images from the channel specified')
sleep(0.3)
print("please enter the mail address associated to your alt account...")
mailrsp = input('')
sleep(0.2)
print("now please enter the password for your alt account")
passrsp = input('')
sleep(0.2)
print("now we need to set the channel id for the alt's dms with you")
dmsrsp = input('')
sleep(0.2)
print('now we need the channelid for the channel where the nsfw is on')
channelidrsp = input('')
sleep(0.2)
print('and for the last part we need the full path of the directory where the nsfw will be saved...')
pathrsp = input('')
print('building config..')
config.set('auth', 'email', f'{mailrsp}')
config.set('auth', 'password', f'{passrsp}')
config.set('interactive channels', f'{dmsrsp}', f'{pathrsp}')
config.set('channels', f'{channelidrsp}', f'{pathrsp}')
with open('config.ini', 'w') as configFile:
    config.write(configFile)
print('config built, now launching the program to download the stuff..')
sleep(0.2)
print('make sure that after the program is ready you go to dms with the alt account and send them "!history" and after he asks for the channel ids specified just send it to him in dms')
sleep(0.3)
print('press enter to confirm that you read the instructions and are ready to start the program')
input('')
os.system('discord-image.exe')
